# -*- coding: utf-8 -*-
"""
Unit test module for export_preliminary_polygons.py (gmd_scripts/export_preliminary_polygons.py).
Auto-generated by scripts/testing/generate_test_stubs.py
"""

import unittest
import importlib
from tests.mocks.qgis_mock import setup_qgis_mock_if_needed

setup_qgis_mock_if_needed()


class TestExportPreliminaryPolygons(unittest.TestCase):
    """Test suite for export_preliminary_polygons.py."""

    def test_module_import(self):
        """Verify that the module imports successfully without syntax or module errors."""
        try:
            mod = importlib.import_module("gmd_scripts.export_preliminary_polygons")
            self.assertIsNotNone(mod, "Module gmd_scripts.export_preliminary_polygons should import successfully.")
        except Exception as err:
            self.fail(f"Failed to import gmd_scripts.export_preliminary_polygons: {err}")

    def test_basic_structure(self):
        """Verify module attributes or functions exist."""
        mod = importlib.import_module("gmd_scripts.export_preliminary_polygons")
        self.assertTrue(hasattr(mod, "__file__"), "Module should have __file__ attribute.")


if __name__ == "__main__":
    unittest.main()
