# -*- coding: utf-8 -*-
"""
Unit test module for psa_lgu_comparison_panel.py (gmd_scripts/psa_lgu_comparison_panel.py).
Auto-generated by scripts/testing/generate_test_stubs.py
"""

import unittest
import importlib
from tests.mocks.qgis_mock import setup_qgis_mock_if_needed, QgsProcessingContext
from tests.mocks.sample_data import create_sample_polygon_layer, create_sample_point_layer

setup_qgis_mock_if_needed()

try:
    from qgis.core import QgsVectorLayer, QgsFields, QgsField, QgsFeature
    from qgis.PyQt.QtCore import QVariant
except ImportError:
    from tests.mocks.qgis_mock import QgsVectorLayer, QgsFields, QgsField, QgsFeature, MockQVariant as QVariant


class TestPsaLguComparisonPanel(unittest.TestCase):
    """Test suite for psa_lgu_comparison_panel.py."""

    def setUp(self):
        self.mod = importlib.import_module("gmd_scripts.psa_lgu_comparison_panel")
        self.sample_polygon = create_sample_polygon_layer("Sample_Polygon_Layer", count=3)
        self.sample_point = create_sample_point_layer("Sample_Point_Layer", count=5)

    def test_module_import(self):
        """Verify that the module imports successfully without syntax or module errors."""
        self.assertIsNotNone(self.mod, "Module gmd_scripts.psa_lgu_comparison_panel should import successfully.")

    def test_sample_data_layer_processing(self):
        """Test module functionality using sample vector layer fixtures."""
        self.assertTrue(self.sample_polygon.isValid(), "Sample polygon layer should be valid.")
        self.assertGreaterEqual(self.sample_polygon.featureCount(), 3)


def _layer_with_fields(name, field_specs):
    """Build a memory layer named *name* with fields from
    field_specs = [(field_name, QVariant type), ...] and no features."""
    fields = QgsFields()
    for fname, ftype in field_specs:
        fields.append(QgsField(fname, ftype))
    layer = QgsVectorLayer("Polygon?crs=EPSG:4326", name, "memory")
    layer.dataProvider().addAttributes(fields)
    layer.updateFields()
    return layer


def _layer_with_features(name, field_specs, rows):
    """Like _layer_with_fields(), but also adds one feature per row in
    *rows* (a list of attribute-value lists, same order as field_specs)."""
    layer = _layer_with_fields(name, field_specs)
    feats = []
    for row in rows:
        feat = QgsFeature(layer.fields())
        feat.setAttributes(list(row))
        feats.append(feat)
    layer.dataProvider().addFeatures(feats)
    return layer


class TestGeocodeFieldResolution(unittest.TestCase):
    """Regression tests for the bug where the review panel's ref_mbi_cases
    filter matched nothing for a barangay that genuinely had cases.

    Root cause: the algorithm appends the matched barangay's first8-
    truncated geocode under the name "geocode", but PSA/LGU source layers
    routinely already carry their OWN "geocode" field (that's exactly what
    Geocode Field auto-detection looks for), so the appended column
    silently lands under a different name ("geocode_2", ...) to avoid a
    collision. The panel was doing a blind case-insensitive "geocode" name
    search, which -- whenever that collision happened -- kept finding the
    ORIGINAL, untruncated source field instead of the correct one. That
    wrong value fed the ref_mbi_cases filter expression, which then never
    matched any case even though the barangay had real ones.

    _geocode_field() fixes this by preferring the GEOCODE_FIELD_PROPERTY
    tag the algorithm now stamps onto its Matched PSA/LGU outputs, which
    names the exact resolved field regardless of collision."""

    def setUp(self):
        self.mod = importlib.import_module("gmd_scripts.psa_lgu_comparison_panel")

    def test_prefers_tagged_property_over_colliding_original_field(self):
        """The regression case itself: both the stale original "geocode"
        field and the algorithm's correctly-tagged "geocode_2" are present
        -- the tag must win."""
        layer = _layer_with_fields("PSA_Matched", [
            ("geocode", QVariant.String),
            ("geocode_2", QVariant.String),
        ])
        layer.setCustomProperty(self.mod.GEOCODE_FIELD_PROPERTY, "geocode_2")
        self.assertEqual(self.mod._geocode_field(layer), "geocode_2")

    def test_falls_back_to_plain_name_when_untagged(self):
        """A layer with no tag at all -- e.g. ref_mbi_cases, which is never
        one of this algorithm's own outputs -- still resolves via a plain
        "geocode" name search, same as before this fix."""
        layer = _layer_with_fields("ref_mbi_cases", [("geocode", QVariant.String)])
        self.assertEqual(self.mod._geocode_field(layer), "geocode")

    def test_ignores_stale_tag_naming_a_field_that_does_not_exist(self):
        """A tag pointing at a field the layer doesn't actually have (e.g.
        left over some other way) falls back to the plain search rather
        than returning nothing."""
        layer = _layer_with_fields("PSA_Matched", [("geocode", QVariant.String)])
        layer.setCustomProperty(self.mod.GEOCODE_FIELD_PROPERTY, "geocode_2")
        self.assertEqual(self.mod._geocode_field(layer), "geocode")

    def test_returns_none_without_any_geocode_field(self):
        layer = _layer_with_fields("Other", [("name", QVariant.String)])
        self.assertIsNone(self.mod._geocode_field(layer))


class TestMbiCasesFilterExpression(unittest.TestCase):
    """Tests for _mbi_cases_filter_expression, including the exact real-
    world scenario reported after the GEOCODE_FIELD_PROPERTY fix: a
    barangay code like "05012010" (8 characters: pppmmbbb) failing to
    match ref_mbi_cases records whose own geocode is the longer, case-
    level form "0501201000000" (pppmmbbb + a case/EA suffix).

    _mbi_cases_filter_expression compares in Python via _first8() and
    returns a "$id IN (...)" expression instead of a QGIS field-comparison
    expression, so this can assert on exact returned content -- unlike a
    QgsExpression.quotedColumnRef()/quotedString()-built expression, which
    the mock can't render faithfully."""

    def setUp(self):
        self.mod = importlib.import_module("gmd_scripts.psa_lgu_comparison_panel")

    def _fake_panel(self, barangay_geocodes):
        panel = object.__new__(self.mod.PsaLguComparisonPanel)
        panel._barangay_geocodes = barangay_geocodes
        return panel

    def test_none_when_barangay_has_no_known_geocode(self):
        layer = _layer_with_fields("ref_mbi_cases", [("geocode", QVariant.String)])
        panel = self._fake_panel({})
        self.assertIsNone(panel._mbi_cases_filter_expression(layer, key=1))

    def test_none_when_layer_has_no_geocode_field(self):
        layer = _layer_with_fields("ref_mbi_cases", [("case_id", QVariant.String)])
        panel = self._fake_panel({1: "00010201"})
        self.assertIsNone(panel._mbi_cases_filter_expression(layer, key=1))

    def test_matches_a_case_level_geocode_by_its_barangay_prefix(self):
        """The exact reported scenario: PSA's own appended geocode is the
        short barangay form "05012010", ref_mbi_cases stores the longer
        case-level form "0501201000000" -- these must still match, and a
        case from a DIFFERENT barangay must not. Features are added in
        this order, so the mock assigns them ids 1, 2, 3 in turn."""
        layer = _layer_with_features("ref_mbi_cases", [("geocode", QVariant.String)], [
            ["0501201000000"],  # id 1, same barangay -- matches
            ["0501201099999"],  # id 2, same barangay, different case suffix -- matches
            ["0501202000000"],  # id 3, different barangay -- must not match
        ])
        panel = self._fake_panel({1: "05012010"})
        self.assertEqual(panel._mbi_cases_filter_expression(layer, key=1), "$id IN (1, 2)")

    def test_returns_always_false_expression_when_barangay_has_no_cases(self):
        """A barangay with zero matching ref_mbi_cases records must show
        none, not silently keep whatever filter the previous barangay
        left behind."""
        layer = _layer_with_features("ref_mbi_cases", [("geocode", QVariant.String)], [
            ["0501202000000"],  # a different barangay entirely
        ])
        panel = self._fake_panel({1: "05012010"})
        self.assertEqual(panel._mbi_cases_filter_expression(layer, key=1), "$id IN (-1)")

    def test_first8_stringifies_non_string_values_before_comparing(self):
        """_first8() applies str() before truncating, so a case geocode
        that happens to come back as a plain Python int/float (rather
        than text) is still compared correctly -- this is what makes the
        comparison consistent regardless of how a particular provider
        happens to type the column, unlike letting a QGIS expression's own
        to_string() decide the rendering at query time."""
        layer = _layer_with_features("ref_mbi_cases", [("geocode", QVariant.String)], [
            [501201000000],  # id 1, stored as a plain Python int, not text
        ])
        panel = self._fake_panel({1: "50120100"})
        self.assertEqual(panel._mbi_cases_filter_expression(layer, key=1), "$id IN (1)")


if __name__ == "__main__":
    unittest.main()
