# -*- coding: utf-8 -*-
"""
Automated Unit Test Generator for GEMMA QGIS Plugin scripts.
Scans gmd_scripts/ and generates test stubs in tests/unit/ for any script missing coverage.

Usage:
  python scripts/testing/generate_test_stubs.py          # Auto-creates missing test stubs
  python scripts/testing/generate_test_stubs.py --check  # Fails if any script is missing a unit test file
"""

import sys
import os
import argparse
from pathlib import Path

# Set up project root in python path
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from tests.mocks.qgis_mock import setup_qgis_mock_if_needed
setup_qgis_mock_if_needed()

TEST_TEMPLATE = '''# -*- coding: utf-8 -*-
"""
Unit test module for {module_name} ({rel_path}).
Auto-generated by scripts/testing/generate_test_stubs.py
"""

import unittest
import importlib
from tests.mocks.qgis_mock import setup_qgis_mock_if_needed, QgsProcessingContext
from tests.mocks.sample_data import create_sample_polygon_layer, create_sample_point_layer

setup_qgis_mock_if_needed()


class Test{class_name}(unittest.TestCase):
    """Test suite for {module_name}."""

    def setUp(self):
        self.mod = importlib.import_module("{import_path}")
        self.sample_polygon = create_sample_polygon_layer("Sample_Polygon_Layer", count=3)
        self.sample_point = create_sample_point_layer("Sample_Point_Layer", count=5)

    def test_module_import(self):
        """Verify that the module imports successfully without syntax or module errors."""
        self.assertIsNotNone(self.mod, "Module {import_path} should import successfully.")

    def test_sample_data_layer_processing(self):
        """Test module functionality using sample vector layer fixtures."""
        self.assertTrue(self.sample_polygon.isValid(), "Sample polygon layer should be valid.")
        self.assertGreaterEqual(self.sample_polygon.featureCount(), 3)


if __name__ == "__main__":
    unittest.main()
'''


def get_target_scripts():
    """Find python scripts in gmd_scripts/ that should have unit tests."""
    gmd_dir = PROJECT_ROOT / "gmd_scripts"
    scripts = []

    if not gmd_dir.exists():
        return scripts

    for file_path in gmd_dir.rglob("*.py"):
        # Ignore __init__.py and deprecated subdirectories
        if file_path.name == "__init__.py" or "deprecated" in file_path.parts:
            continue
        scripts.append(file_path)

    return sorted(scripts)


def to_snake_case_name(file_path):
    """Convert filename to test file name e.g. gmdhelpers.py -> test_gmdhelpers.py."""
    stem = file_path.stem
    if stem.startswith("test_"):
        return f"{stem}.py"
    return f"test_{stem}.py"


def to_class_name(stem):
    """Convert file stem to CamelCase class name."""
    clean = stem.replace("test_", "")
    parts = clean.split("_")
    return "".join(p.capitalize() for p in parts if p)


def run_generator(check_only=False):
    target_scripts = get_target_scripts()
    unit_tests_dir = PROJECT_ROOT / "tests" / "unit"
    unit_tests_dir.mkdir(parents=True, exist_ok=True)

    missing_tests = []
    created_tests = []

    for script_path in target_scripts:
        test_filename = to_snake_case_name(script_path)
        test_path = unit_tests_dir / test_filename

        if not test_path.exists():
            missing_tests.append((script_path, test_path))
            if not check_only:
                # Generate test file
                rel_path = script_path.relative_to(PROJECT_ROOT).as_posix()
                rel_import = rel_path.replace(".py", "").replace("/", ".")
                class_name = to_class_name(script_path.stem)

                content = TEST_TEMPLATE.format(
                    module_name=script_path.name,
                    rel_path=rel_path,
                    import_path=rel_import,
                    class_name=class_name
                )

                test_path.write_text(content, encoding="utf-8")
                created_tests.append(test_path)

    if check_only:
        if missing_tests:
            print(f"[CHECK FAILED] {len(missing_tests)} script(s) are missing unit test files in tests/unit/:")
            for script_path, test_path in missing_tests:
                print(f"  - Script: {script_path.relative_to(PROJECT_ROOT)} (Expected test: {test_path.relative_to(PROJECT_ROOT)})")
            return False
        else:
            print("[CHECK PASSED] All scripts in gmd_scripts/ have corresponding unit test files.")
            return True

    print(f"[INFO] Scanned {len(target_scripts)} scripts in gmd_scripts/.")
    if created_tests:
        print(f"[SUCCESS] Generated {len(created_tests)} new unit test stub(s):")
        for tp in created_tests:
            print(f"  + {tp.relative_to(PROJECT_ROOT)}")
    else:
        print("[INFO] All scripts already have unit test files in tests/unit/.")

    return True


def main():
    parser = argparse.ArgumentParser(description="Auto-generate unit test stubs for GEMMA plugin scripts.")
    parser.add_argument("--check", action="store_true", help="Check if all scripts have unit tests without creating them.")
    args = parser.parse_args()

    success = run_generator(check_only=args.check)
    if not success:
        sys.exit(1)


if __name__ == "__main__":
    main()
